services:
  scraper-api:
    build: .
    image: scraper-api:latest
    container_name: scraper-api
    restart: unless-stopped
    networks:
      1panel-network:
        ipv4_address: 172.18.0.10
    volumes:
      - ./cache:/app/cache
    environment:
      - NODE_ENV=production
      - PORT=3200
      - CAMOFOX_URL=http://172.18.0.5:9377
    expose:
      - "3200"

networks:
  1panel-network:
    external: true
